### ISSUE TITLE
https://blog.raxianch.moe/

### ISSUE THREAD

**Issue by CCKNBC** [ccknbc-actions/blogroll#2]
**标题请书写你的链接，不要写其他内容**

```yaml
# 显示名称
name: 快乐咸鱼の RaXianch 窝

# 跳转地址
link: https://blog.raxianch.moe/

# 你的头像
avatar: https://q1.qlogo.cn/g?b=qq&nk=1025212779&s=5

# 你的描述
descr: 为之则易，不为则难

#------------------------------#
#       以下字段为选填字段       #

# 边框及鼠标悬停的背景颜色，允许设置渐变色
--primary-color: #49b1f5

# 昵称和描述颜色，不允许设置渐变色
--namecolor: 

# 鼠标悬停的昵称和描述颜色，不允许设置渐变色
--namecolorHover: 

# 边框大小
border-width: 0px

# 边框样式
border-style: solid

# 鼠标悬停头像旋转角度
--primary-rotate: 0deg

# 边框动画 参考 https://developer.mozilla.org/zh-CN/docs/Web/CSS/animation
# 内置动画：borderFlash（边框闪现）、link_custom1(跑马灯)、link_custom(主颜色呼吸灯)
animation: borderFlash 0s infinite alternate

# 头像动画 参考 https://developer.mozilla.org/zh-CN/docs/Web/CSS/animation
# 内置动画：auto_rotate_left（左旋转）、auto_rotate_right（右旋转）
img_animation: auto_rotate_right 0s linear infinite

# 风格 可选项 item 和 card
card_style: item

# 自定义网站截图，当样式为 card 时可以自定义网站截图
# 如果您的站点不常更新，可留空，会使用默认接口 https://image.thum.io/get/width/1024/crop/768/https://blog.ccknbc.cc
# 如果您的站点加载完毕耗时较长，请自行替换为此接口中网址部分填入 https://s0.wordpress.com/mshots/v1/https://blog.ccknbc.cc?w=1280&h=960
# 如果您知道其他好用的接口，欢迎给我留言，谢谢
screenshot: 
```
