### ISSUE TITLE
https://6ing.xyz

### ISSUE THREAD

**Issue by mjcfx** [ccknbc-actions/blogroll#25]
```yaml
- name: Xc's Blog
    link: https://6ing.xyz/
    avatar: https://cdn.jsdelivr.net/gh/mjcfx/picgo/img/qqtou.jpg
    descr: 欢迎您的访问！
    siteshot: https://cdn.jsdelivr.net/gh/mjcfx/picgo/img/xc.png
```
